;; cocktails:   70
;; ingredients: 10
;; shots:       10
(define (problem prob)
 (:domain barman)
 (:objects 
     shaker1 - shaker
     left right - hand
     shot1 shot2 shot3 shot4 shot5 shot6 shot7 shot8 shot9 shot10 - shot
     ingredient1 ingredient2 ingredient3 ingredient4 ingredient5 ingredient6 ingredient7 ingredient8 ingredient9 ingredient10 - ingredient
     cocktail1 cocktail2 cocktail3 cocktail4 cocktail5 cocktail6 cocktail7 cocktail8 cocktail9 cocktail10 cocktail11 cocktail12 cocktail13 cocktail14 cocktail15 cocktail16 cocktail17 cocktail18 cocktail19 cocktail20 cocktail21 cocktail22 cocktail23 cocktail24 cocktail25 cocktail26 cocktail27 cocktail28 cocktail29 cocktail30 cocktail31 cocktail32 cocktail33 cocktail34 cocktail35 cocktail36 cocktail37 cocktail38 cocktail39 cocktail40 cocktail41 cocktail42 cocktail43 cocktail44 cocktail45 cocktail46 cocktail47 cocktail48 cocktail49 cocktail50 cocktail51 cocktail52 cocktail53 cocktail54 cocktail55 cocktail56 cocktail57 cocktail58 cocktail59 cocktail60 cocktail61 cocktail62 cocktail63 cocktail64 cocktail65 cocktail66 cocktail67 cocktail68 cocktail69 cocktail70 - cocktail
     dispenser1 dispenser2 dispenser3 dispenser4 dispenser5 dispenser6 dispenser7 dispenser8 dispenser9 dispenser10 - dispenser
     l0 l1 l2 - level
)
 (:init 
  (ontable shaker1)
  (ontable shot1)
  (ontable shot2)
  (ontable shot3)
  (ontable shot4)
  (ontable shot5)
  (ontable shot6)
  (ontable shot7)
  (ontable shot8)
  (ontable shot9)
  (ontable shot10)
  (dispenses dispenser1 ingredient1)
  (dispenses dispenser2 ingredient2)
  (dispenses dispenser3 ingredient3)
  (dispenses dispenser4 ingredient4)
  (dispenses dispenser5 ingredient5)
  (dispenses dispenser6 ingredient6)
  (dispenses dispenser7 ingredient7)
  (dispenses dispenser8 ingredient8)
  (dispenses dispenser9 ingredient9)
  (dispenses dispenser10 ingredient10)
  (clean shaker1)
  (clean shot1)
  (clean shot2)
  (clean shot3)
  (clean shot4)
  (clean shot5)
  (clean shot6)
  (clean shot7)
  (clean shot8)
  (clean shot9)
  (clean shot10)
  (empty shaker1)
  (empty shot1)
  (empty shot2)
  (empty shot3)
  (empty shot4)
  (empty shot5)
  (empty shot6)
  (empty shot7)
  (empty shot8)
  (empty shot9)
  (empty shot10)
  (handempty left)
  (handempty right)
  (shaker-empty-level shaker1 l0)
  (shaker-level shaker1 l0)
  (next l0 l1)
  (next l1 l2)
  (cocktail-part1 cocktail1 ingredient5)
  (cocktail-part2 cocktail1 ingredient7)
  (cocktail-part1 cocktail2 ingredient10)
  (cocktail-part2 cocktail2 ingredient2)
  (cocktail-part1 cocktail3 ingredient8)
  (cocktail-part2 cocktail3 ingredient5)
  (cocktail-part1 cocktail4 ingredient3)
  (cocktail-part2 cocktail4 ingredient6)
  (cocktail-part1 cocktail5 ingredient1)
  (cocktail-part2 cocktail5 ingredient6)
  (cocktail-part1 cocktail6 ingredient10)
  (cocktail-part2 cocktail6 ingredient2)
  (cocktail-part1 cocktail7 ingredient4)
  (cocktail-part2 cocktail7 ingredient7)
  (cocktail-part1 cocktail8 ingredient7)
  (cocktail-part2 cocktail8 ingredient8)
  (cocktail-part1 cocktail9 ingredient4)
  (cocktail-part2 cocktail9 ingredient2)
  (cocktail-part1 cocktail10 ingredient3)
  (cocktail-part2 cocktail10 ingredient1)
  (cocktail-part1 cocktail11 ingredient9)
  (cocktail-part2 cocktail11 ingredient8)
  (cocktail-part1 cocktail12 ingredient4)
  (cocktail-part2 cocktail12 ingredient8)
  (cocktail-part1 cocktail13 ingredient3)
  (cocktail-part2 cocktail13 ingredient2)
  (cocktail-part1 cocktail14 ingredient3)
  (cocktail-part2 cocktail14 ingredient8)
  (cocktail-part1 cocktail15 ingredient9)
  (cocktail-part2 cocktail15 ingredient3)
  (cocktail-part1 cocktail16 ingredient8)
  (cocktail-part2 cocktail16 ingredient3)
  (cocktail-part1 cocktail17 ingredient2)
  (cocktail-part2 cocktail17 ingredient10)
  (cocktail-part1 cocktail18 ingredient5)
  (cocktail-part2 cocktail18 ingredient4)
  (cocktail-part1 cocktail19 ingredient9)
  (cocktail-part2 cocktail19 ingredient5)
  (cocktail-part1 cocktail20 ingredient3)
  (cocktail-part2 cocktail20 ingredient7)
  (cocktail-part1 cocktail21 ingredient5)
  (cocktail-part2 cocktail21 ingredient6)
  (cocktail-part1 cocktail22 ingredient4)
  (cocktail-part2 cocktail22 ingredient1)
  (cocktail-part1 cocktail23 ingredient4)
  (cocktail-part2 cocktail23 ingredient2)
  (cocktail-part1 cocktail24 ingredient8)
  (cocktail-part2 cocktail24 ingredient3)
  (cocktail-part1 cocktail25 ingredient1)
  (cocktail-part2 cocktail25 ingredient10)
  (cocktail-part1 cocktail26 ingredient2)
  (cocktail-part2 cocktail26 ingredient6)
  (cocktail-part1 cocktail27 ingredient7)
  (cocktail-part2 cocktail27 ingredient3)
  (cocktail-part1 cocktail28 ingredient1)
  (cocktail-part2 cocktail28 ingredient10)
  (cocktail-part1 cocktail29 ingredient2)
  (cocktail-part2 cocktail29 ingredient1)
  (cocktail-part1 cocktail30 ingredient3)
  (cocktail-part2 cocktail30 ingredient5)
  (cocktail-part1 cocktail31 ingredient10)
  (cocktail-part2 cocktail31 ingredient9)
  (cocktail-part1 cocktail32 ingredient9)
  (cocktail-part2 cocktail32 ingredient5)
  (cocktail-part1 cocktail33 ingredient3)
  (cocktail-part2 cocktail33 ingredient7)
  (cocktail-part1 cocktail34 ingredient3)
  (cocktail-part2 cocktail34 ingredient1)
  (cocktail-part1 cocktail35 ingredient3)
  (cocktail-part2 cocktail35 ingredient1)
  (cocktail-part1 cocktail36 ingredient3)
  (cocktail-part2 cocktail36 ingredient8)
  (cocktail-part1 cocktail37 ingredient9)
  (cocktail-part2 cocktail37 ingredient5)
  (cocktail-part1 cocktail38 ingredient2)
  (cocktail-part2 cocktail38 ingredient1)
  (cocktail-part1 cocktail39 ingredient7)
  (cocktail-part2 cocktail39 ingredient1)
  (cocktail-part1 cocktail40 ingredient5)
  (cocktail-part2 cocktail40 ingredient4)
  (cocktail-part1 cocktail41 ingredient4)
  (cocktail-part2 cocktail41 ingredient1)
  (cocktail-part1 cocktail42 ingredient8)
  (cocktail-part2 cocktail42 ingredient1)
  (cocktail-part1 cocktail43 ingredient1)
  (cocktail-part2 cocktail43 ingredient5)
  (cocktail-part1 cocktail44 ingredient8)
  (cocktail-part2 cocktail44 ingredient7)
  (cocktail-part1 cocktail45 ingredient3)
  (cocktail-part2 cocktail45 ingredient7)
  (cocktail-part1 cocktail46 ingredient6)
  (cocktail-part2 cocktail46 ingredient10)
  (cocktail-part1 cocktail47 ingredient4)
  (cocktail-part2 cocktail47 ingredient3)
  (cocktail-part1 cocktail48 ingredient7)
  (cocktail-part2 cocktail48 ingredient2)
  (cocktail-part1 cocktail49 ingredient10)
  (cocktail-part2 cocktail49 ingredient1)
  (cocktail-part1 cocktail50 ingredient9)
  (cocktail-part2 cocktail50 ingredient5)
  (cocktail-part1 cocktail51 ingredient10)
  (cocktail-part2 cocktail51 ingredient3)
  (cocktail-part1 cocktail52 ingredient3)
  (cocktail-part2 cocktail52 ingredient6)
  (cocktail-part1 cocktail53 ingredient6)
  (cocktail-part2 cocktail53 ingredient8)
  (cocktail-part1 cocktail54 ingredient1)
  (cocktail-part2 cocktail54 ingredient5)
  (cocktail-part1 cocktail55 ingredient8)
  (cocktail-part2 cocktail55 ingredient5)
  (cocktail-part1 cocktail56 ingredient7)
  (cocktail-part2 cocktail56 ingredient10)
  (cocktail-part1 cocktail57 ingredient3)
  (cocktail-part2 cocktail57 ingredient5)
  (cocktail-part1 cocktail58 ingredient8)
  (cocktail-part2 cocktail58 ingredient7)
  (cocktail-part1 cocktail59 ingredient3)
  (cocktail-part2 cocktail59 ingredient10)
  (cocktail-part1 cocktail60 ingredient4)
  (cocktail-part2 cocktail60 ingredient10)
  (cocktail-part1 cocktail61 ingredient2)
  (cocktail-part2 cocktail61 ingredient8)
  (cocktail-part1 cocktail62 ingredient7)
  (cocktail-part2 cocktail62 ingredient4)
  (cocktail-part1 cocktail63 ingredient1)
  (cocktail-part2 cocktail63 ingredient4)
  (cocktail-part1 cocktail64 ingredient6)
  (cocktail-part2 cocktail64 ingredient8)
  (cocktail-part1 cocktail65 ingredient5)
  (cocktail-part2 cocktail65 ingredient10)
  (cocktail-part1 cocktail66 ingredient9)
  (cocktail-part2 cocktail66 ingredient5)
  (cocktail-part1 cocktail67 ingredient6)
  (cocktail-part2 cocktail67 ingredient3)
  (cocktail-part1 cocktail68 ingredient3)
  (cocktail-part2 cocktail68 ingredient5)
  (cocktail-part1 cocktail69 ingredient1)
  (cocktail-part2 cocktail69 ingredient8)
  (cocktail-part1 cocktail70 ingredient8)
  (cocktail-part2 cocktail70 ingredient2)
)
 (:goal
  (and
     (contains shot1 cocktail38)
     (contains shot2 cocktail35)
     (contains shot3 cocktail5)
     (contains shot4 cocktail13)
     (contains shot5 cocktail64)
     (contains shot6 cocktail44)
     (contains shot7 cocktail12)
     (contains shot8 cocktail60)
     (contains shot9 cocktail16)
     (contains shot10 cocktail62)
     (contains shot11 cocktail48)
     (contains shot12 cocktail43)
     (contains shot13 cocktail8)
     (contains shot14 cocktail41)
     (contains shot15 cocktail52)
     (contains shot16 cocktail63)
     (contains shot17 cocktail55)
     (contains shot18 cocktail65)
     (contains shot19 cocktail4)
     (contains shot20 cocktail9)
     (contains shot21 cocktail2)
     (contains shot22 cocktail68)
     (contains shot23 cocktail26)
     (contains shot24 cocktail66)
     (contains shot25 cocktail42)
     (contains shot26 cocktail61)
     (contains shot27 cocktail47)
     (contains shot28 cocktail39)
     (contains shot29 cocktail51)
     (contains shot30 cocktail53)
     (contains shot31 cocktail69)
     (contains shot32 cocktail24)
     (contains shot33 cocktail11)
     (contains shot34 cocktail54)
     (contains shot35 cocktail59)
     (contains shot36 cocktail22)
     (contains shot37 cocktail36)
     (contains shot38 cocktail37)
     (contains shot39 cocktail15)
     (contains shot40 cocktail30)
     (contains shot41 cocktail7)
     (contains shot42 cocktail21)
     (contains shot43 cocktail58)
     (contains shot44 cocktail1)
     (contains shot45 cocktail50)
     (contains shot46 cocktail45)
     (contains shot47 cocktail34)
     (contains shot48 cocktail23)
     (contains shot49 cocktail28)
     (contains shot50 cocktail3)
     (contains shot51 cocktail33)
     (contains shot52 cocktail19)
     (contains shot53 cocktail27)
     (contains shot54 cocktail29)
     (contains shot55 cocktail70)
     (contains shot56 cocktail14)
     (contains shot57 cocktail49)
     (contains shot58 cocktail6)
     (contains shot59 cocktail10)
     (contains shot60 cocktail17)
     (contains shot61 cocktail18)
     (contains shot62 cocktail32)
     (contains shot63 cocktail25)
     (contains shot64 cocktail40)
     (contains shot65 cocktail46)
     (contains shot66 cocktail67)
     (contains shot67 cocktail56)
     (contains shot68 cocktail20)
     (contains shot69 cocktail57)
     (contains shot70 cocktail31)
)))
